# *** WARNING: DO NOT MODIFY *** This is a generated Python source code!
#
# Generated by LF-ET 2.4.1 (260127a), https://www.lohrfink.de/lfet
# From decision table
# "E:/data/schweier/rbtfrmwrk/robotframework-syndata/lfet/ItemBuilderEngineFaker.lfet"
# 13.02.2026 15:13
#
# Changes to this code resulting from refactorings can be synchronised
# with LF-ET using the function "Scrapbook Import".
#
# Prolog Decision Table ---->
# $$BasicIndentLevel=2
from robot.libraries.BuiltIn import BuiltIn

from faker import Faker
from .country import Country

class ItemBuilderEngineFaker:

    @staticmethod
    def execute(instance, localization: str, keyword: str, item: str, item_data: dict):
        fake = Faker(localization)
        # Prolog Decision Table <----
        _item_builder_engine_faker_rule_executed: bool = False
        # Condition B01/01: Context is / None / There is no set context.
        if ( None == instance.Get_Context() ):
            # Condition B02/01: Requestes item code / address.address / An address consisting of street, house number, postal code, and city should be returned in two lines.
            if ( "address.address" == item ):
                # Rule R01 ---->
                _item_builder_engine_faker_rule_executed = True
                # Trace ---->
                instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineFaker (20260213.151301), rule 1 of 31 has been executed", "DEBUG")
                # Trace <----
                # Action A01/01: Create local data / address.address / An address consisting of street, house number, postal code, and city should be returned in two lines.
                local_data = fake.address()
                # Action A08/04: Return created data / local / The locally generated data will be returned
                return local_data
                # Rule R01 <----
            # Condition B02/02: Requestes item code / address.address_country / An address consisting of street, house number, postal code, city, and state should be returned in three lines.
            elif ( "address.address_country" == item ):
                # Rule R02 ---->
                _item_builder_engine_faker_rule_executed = True
                # Trace ---->
                instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineFaker (20260213.151301), rule 2 of 31 has been executed", "DEBUG")
                # Trace <----
                # Action A01/02: Create local data / address.address_country / An address consisting of street, house number, postal code, city, and state should be returned in three lines.
                local_data = f"{fake.address()}\n{fake.current_country()}"
                # Action A08/04: Return created data / local / The locally generated data will be returned
                return local_data
                # Rule R02 <----
            # Condition B02/03: Requestes item code / address.street_address / An address consisting of a street name and house number should be returned.
            elif ( "address.street_address" == item ):
                # Rule R03 ---->
                _item_builder_engine_faker_rule_executed = True
                # Trace ---->
                instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineFaker (20260213.151301), rule 3 of 31 has been executed", "DEBUG")
                # Trace <----
                # Action A01/03: Create local data / address.street_address / An address consisting of a street name and house number should be returned.
                local_data = fake.street_address()
                # Action A08/04: Return created data / local / The locally generated data will be returned
                return local_data
                # Rule R03 <----
            # Condition B02/04: Requestes item code / address.street / A street name shuold be returned.
            elif ( "address.street" == item ):
                # Rule R04 ---->
                _item_builder_engine_faker_rule_executed = True
                # Trace ---->
                instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineFaker (20260213.151301), rule 4 of 31 has been executed", "DEBUG")
                # Trace <----
                # Action A01/04: Create local data / address.street / A street name shuold be returned.
                local_data = fake.street_name()
                # Action A08/04: Return created data / local / The locally generated data will be returned
                return local_data
                # Rule R04 <----
            # Condition B02/05: Requestes item code / address.house_number / A house number should be returned.
            elif ( "address.house_number" == item ):
                # Rule R05 ---->
                _item_builder_engine_faker_rule_executed = True
                # Trace ---->
                instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineFaker (20260213.151301), rule 5 of 31 has been executed", "DEBUG")
                # Trace <----
                # Action A01/05: Create local data / address.house_number / A house number should be returned.
                local_data = fake.street_address()
                # Action A08/04: Return created data / local / The locally generated data will be returned
                return local_data
                # Rule R05 <----
            # Condition B02/06: Requestes item code / address.postcode_city / A city with its corresponding postal code should be returned.
            elif ( "address.postcode_city" == item ):
                # Rule R06 ---->
                _item_builder_engine_faker_rule_executed = True
                # Trace ---->
                instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineFaker (20260213.151301), rule 6 of 31 has been executed", "DEBUG")
                # Trace <----
                # Action A01/06: Create local data / address.postcode_city / A city with its corresponding postal code should be returned.
                lines = fake.address().splitlines()
                if(1 < len(lines)):
                    local_data = lines[-1]
                else:
                    local_data = f"{fake.postcode()} {fake.city()}"
                # Action A08/04: Return created data / local / The locally generated data will be returned
                return local_data
                # Rule R06 <----
            # Condition B02/07: Requestes item code / address.postcode / A postal code should be returned.
            elif ( "address.postcode" == item ):
                # Rule R07 ---->
                _item_builder_engine_faker_rule_executed = True
                # Trace ---->
                instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineFaker (20260213.151301), rule 7 of 31 has been executed", "DEBUG")
                # Trace <----
                # Action A01/07: Create local data / address.postcode / A postal code should be returned.
                local_data = fake.postcode()
                # Action A08/04: Return created data / local / The locally generated data will be returned
                return local_data
                # Rule R07 <----
            # Condition B02/08: Requestes item code / address.city / A city should be returned.
            elif ( "address.city" == item ):
                # Rule R08 ---->
                _item_builder_engine_faker_rule_executed = True
                # Trace ---->
                instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineFaker (20260213.151301), rule 8 of 31 has been executed", "DEBUG")
                # Trace <----
                # Action A01/08: Create local data / address.city / A city is to be returned.
                local_data = fake.city()
                # Action A08/04: Return created data / local / The locally generated data will be returned
                return local_data
                # Rule R08 <----
            # Condition B02/09: Requestes item code / address.state / A federal state should be returned.
            elif ( "address.state" == item ):
                # Rule R09 ---->
                _item_builder_engine_faker_rule_executed = True
                # Trace ---->
                instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineFaker (20260213.151301), rule 9 of 31 has been executed", "DEBUG")
                # Trace <----
                # Action A01/09: Create local data / address.state / A federal state is to be returned.
                local_data = ""
                # Action A06/01: Print Log Message / not_supported / Infomation that item is not supported.
                instance.add_rbt_log_message("The keyword \"{keyword}\" is not supported for localization \"{localization}\".", "INFO")
                # Action A08/04: Return created data / local / The locally generated data will be returned
                return local_data
                # Rule R09 <----
            # Condition B02/10: Requestes item code / address.country / The country based on localization should be returned
            elif ( "address.country" == item ):
                # Rule R10 ---->
                _item_builder_engine_faker_rule_executed = True
                # Trace ---->
                instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineFaker (20260213.151301), rule 10 of 31 has been executed", "DEBUG")
                # Trace <----
                # Action A01/10: Create local data / address.country / The country name based on localization should be returned
                local_data = Country.get_country_name(item_data, localization.split("_")[0].lower())
                # Action A08/04: Return created data / local / The locally generated data will be returned
                return local_data
                # Rule R10 <----
            # Condition B02/11: Requestes item code / address.country_code / The country code based on localization should be returned
            elif ( "address.country_code" == item ):
                # Rule R11 ---->
                _item_builder_engine_faker_rule_executed = True
                # Trace ---->
                instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineFaker (20260213.151301), rule 11 of 31 has been executed", "DEBUG")
                # Trace <----
                # Action A01/11: Create local data / address.country_code / The country code based on localization should be returned
                local_data = Country.get_country_code(item_data, "ALPHA-2")
                # Action A08/04: Return created data / local / The locally generated data will be returned
                return local_data
                # Rule R11 <----
            # Condition B02/12: Requestes item code / person.name / A complete name consisting of first name and last name should be returned.
            elif ( "person.name" == item ):
                # Rule R12 ---->
                _item_builder_engine_faker_rule_executed = True
                # Trace ---->
                instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineFaker (20260213.151301), rule 12 of 31 has been executed", "DEBUG")
                # Trace <----
                # Action A08/01: Return created data / person.name /
                match item_data.get("sex"):
                    case "f":
                        return fake.name_female()
                    case "m":
                        return fake.name_male()
                    case "d":
                        return fake.name_nonbinary()
                    case _:
                        return fake.name()
                # Rule R12 <----
            # Condition B02/13: Requestes item code / person.first_name / A first name should be returned.
            elif ( "person.first_name" == item ):
                # Rule R13 ---->
                _item_builder_engine_faker_rule_executed = True
                # Trace ---->
                instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineFaker (20260213.151301), rule 13 of 31 has been executed", "DEBUG")
                # Trace <----
                # Action A08/02: Return created data / person.first_name /
                match item_data.get("sex"):
                    case "f":
                        return fake.first_name_female()
                    case "m":
                        return fake.first_name_male()
                    case "d":
                        return fake.first_name_nonbinary()
                    case _:
                        return fake.first_name()
                # Rule R13 <----
            # Condition B02/14: Requestes item code / person.last_name / A last name should be returned.
            elif ( "person.last_name" == item ):
                # Rule R14 ---->
                _item_builder_engine_faker_rule_executed = True
                # Trace ---->
                instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineFaker (20260213.151301), rule 14 of 31 has been executed", "DEBUG")
                # Trace <----
                # Action A08/03: Return created data / person.last_name /
                match item_data.get("sex"):
                    case "f":
                        return fake.last_name_female()
                    case "m":
                        return fake.last_name_male()
                    case "d":
                        return fake.last_name_nonbinary()
                    case _:
                        return fake.last_name()
                # Rule R14 <----
        else:
            # Condition B02/01: Requestes item code / address.address / An address consisting of street, house number, postal code, and city should be returned in two lines.
            if ( "address.address" == item ):
                # Rule R15 ---->
                _item_builder_engine_faker_rule_executed = True
                # Trace ---->
                instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineFaker (20260213.151301), rule 15 of 31 has been executed", "DEBUG")
                # Trace <----
                # Action A01/01: Create local data / address.address / An address consisting of street, house number, postal code, and city should be returned in two lines.
                local_data = fake.address()
                # Action A05/01: Add to context / local / The local data will be stored into context
                instance.add_item(item, local_data)
                # Action A06/02: Print Log Message / not_consistent / The generated test data is not necessarily consistent with other dependent values!
                instance.add_rbt_log_message("The generated test data is not necessarily consistent with other dependent values!", "INFO")
                # Action A07/01: Return Item from context / item / Aktion ausführen
                return instance.get_item(item)
                # Rule R15 <----
            # Condition B02/02: Requestes item code / address.address_country / An address consisting of street, house number, postal code, city, and state should be returned in three lines.
            elif ( "address.address_country" == item ):
                # Rule R16 ---->
                _item_builder_engine_faker_rule_executed = True
                # Trace ---->
                instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineFaker (20260213.151301), rule 16 of 31 has been executed", "DEBUG")
                # Trace <----
                # Action A01/02: Create local data / address.address_country / An address consisting of street, house number, postal code, city, and state should be returned in three lines.
                local_data = f"{fake.address()}\n{fake.current_country()}"
                # Action A05/01: Add to context / local / The local data will be stored into context
                instance.add_item(item, local_data)
                # Action A06/02: Print Log Message / not_consistent / The generated test data is not necessarily consistent with other dependent values!
                instance.add_rbt_log_message("The generated test data is not necessarily consistent with other dependent values!", "INFO")
                # Action A07/01: Return Item from context / item / Aktion ausführen
                return instance.get_item(item)
                # Rule R16 <----
            # Condition B02/03: Requestes item code / address.street_address / An address consisting of a street name and house number should be returned.
            elif ( "address.street_address" == item ):
                # Rule R17 ---->
                _item_builder_engine_faker_rule_executed = True
                # Trace ---->
                instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineFaker (20260213.151301), rule 17 of 31 has been executed", "DEBUG")
                # Trace <----
                # Action A01/03: Create local data / address.street_address / An address consisting of a street name and house number should be returned.
                local_data = fake.street_address()
                # Action A05/01: Add to context / local / The local data will be stored into context
                instance.add_item(item, local_data)
                # Action A06/02: Print Log Message / not_consistent / The generated test data is not necessarily consistent with other dependent values!
                instance.add_rbt_log_message("The generated test data is not necessarily consistent with other dependent values!", "INFO")
                # Action A07/01: Return Item from context / item / Aktion ausführen
                return instance.get_item(item)
                # Rule R17 <----
            # Condition B02/04: Requestes item code / address.street / A street name shuold be returned.
            elif ( "address.street" == item ):
                # Rule R18 ---->
                _item_builder_engine_faker_rule_executed = True
                # Trace ---->
                instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineFaker (20260213.151301), rule 18 of 31 has been executed", "DEBUG")
                # Trace <----
                # Action A01/04: Create local data / address.street / A street name shuold be returned.
                local_data = fake.street_name()
                # Action A05/01: Add to context / local / The local data will be stored into context
                instance.add_item(item, local_data)
                # Action A06/02: Print Log Message / not_consistent / The generated test data is not necessarily consistent with other dependent values!
                instance.add_rbt_log_message("The generated test data is not necessarily consistent with other dependent values!", "INFO")
                # Action A07/01: Return Item from context / item / Aktion ausführen
                return instance.get_item(item)
                # Rule R18 <----
            # Condition B02/05: Requestes item code / address.house_number / A house number should be returned.
            elif ( "address.house_number" == item ):
                # Rule R19 ---->
                _item_builder_engine_faker_rule_executed = True
                # Trace ---->
                instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineFaker (20260213.151301), rule 19 of 31 has been executed", "DEBUG")
                # Trace <----
                # Action A01/05: Create local data / address.house_number / A house number should be returned.
                local_data = fake.street_address()
                # Action A05/01: Add to context / local / The local data will be stored into context
                instance.add_item(item, local_data)
                # Action A06/02: Print Log Message / not_consistent / The generated test data is not necessarily consistent with other dependent values!
                instance.add_rbt_log_message("The generated test data is not necessarily consistent with other dependent values!", "INFO")
                # Action A07/01: Return Item from context / item / Aktion ausführen
                return instance.get_item(item)
                # Rule R19 <----
            # Condition B02/06: Requestes item code / address.postcode_city / A city with its corresponding postal code should be returned.
            elif ( "address.postcode_city" == item ):
                # Rule R20 ---->
                _item_builder_engine_faker_rule_executed = True
                # Trace ---->
                instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineFaker (20260213.151301), rule 20 of 31 has been executed", "DEBUG")
                # Trace <----
                # Action A01/06: Create local data / address.postcode_city / A city with its corresponding postal code should be returned.
                lines = fake.address().splitlines()
                if(1 < len(lines)):
                    local_data = lines[-1]
                else:
                    local_data = f"{fake.postcode()} {fake.city()}"
                # Action A05/01: Add to context / local / The local data will be stored into context
                instance.add_item(item, local_data)
                # Action A06/02: Print Log Message / not_consistent / The generated test data is not necessarily consistent with other dependent values!
                instance.add_rbt_log_message("The generated test data is not necessarily consistent with other dependent values!", "INFO")
                # Action A07/01: Return Item from context / item / Aktion ausführen
                return instance.get_item(item)
                # Rule R20 <----
            # Condition B02/07: Requestes item code / address.postcode / A postal code should be returned.
            elif ( "address.postcode" == item ):
                # Rule R21 ---->
                _item_builder_engine_faker_rule_executed = True
                # Trace ---->
                instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineFaker (20260213.151301), rule 21 of 31 has been executed", "DEBUG")
                # Trace <----
                # Action A01/07: Create local data / address.postcode / A postal code should be returned.
                local_data = fake.postcode()
                # Action A05/01: Add to context / local / The local data will be stored into context
                instance.add_item(item, local_data)
                # Action A06/02: Print Log Message / not_consistent / The generated test data is not necessarily consistent with other dependent values!
                instance.add_rbt_log_message("The generated test data is not necessarily consistent with other dependent values!", "INFO")
                # Action A07/01: Return Item from context / item / Aktion ausführen
                return instance.get_item(item)
                # Rule R21 <----
            # Condition B02/08: Requestes item code / address.city / A city should be returned.
            elif ( "address.city" == item ):
                # Rule R22 ---->
                _item_builder_engine_faker_rule_executed = True
                # Trace ---->
                instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineFaker (20260213.151301), rule 22 of 31 has been executed", "DEBUG")
                # Trace <----
                # Action A01/08: Create local data / address.city / A city is to be returned.
                local_data = fake.city()
                # Action A05/01: Add to context / local / The local data will be stored into context
                instance.add_item(item, local_data)
                # Action A06/02: Print Log Message / not_consistent / The generated test data is not necessarily consistent with other dependent values!
                instance.add_rbt_log_message("The generated test data is not necessarily consistent with other dependent values!", "INFO")
                # Action A07/01: Return Item from context / item / Aktion ausführen
                return instance.get_item(item)
                # Rule R22 <----
            # Condition B02/09: Requestes item code / address.state / A federal state should be returned.
            elif ( "address.state" == item ):
                # Rule R23 ---->
                _item_builder_engine_faker_rule_executed = True
                # Trace ---->
                instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineFaker (20260213.151301), rule 23 of 31 has been executed", "DEBUG")
                # Trace <----
                # Action A01/09: Create local data / address.state / A federal state is to be returned.
                local_data = ""
                # Action A06/01: Print Log Message / not_supported / Infomation that item is not supported.
                instance.add_rbt_log_message("The keyword \"{keyword}\" is not supported for localization \"{localization}\".", "INFO")
                # Action A07/01: Return Item from context / item / Aktion ausführen
                return instance.get_item(item)
                # Rule R23 <----
            # Condition B02/10: Requestes item code / address.country / The country based on localization should be returned
            elif ( "address.country" == item ):
                # Rule R24 ---->
                _item_builder_engine_faker_rule_executed = True
                # Trace ---->
                instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineFaker (20260213.151301), rule 24 of 31 has been executed", "DEBUG")
                # Trace <----
                # Action A01/10: Create local data / address.country / The country name based on localization should be returned
                local_data = Country.get_country_name(item_data, localization.split("_")[0].lower())
                # Action A05/01: Add to context / local / The local data will be stored into context
                instance.add_item(item, local_data)
                # Action A06/02: Print Log Message / not_consistent / The generated test data is not necessarily consistent with other dependent values!
                instance.add_rbt_log_message("The generated test data is not necessarily consistent with other dependent values!", "INFO")
                # Action A07/01: Return Item from context / item / Aktion ausführen
                return instance.get_item(item)
                # Rule R24 <----
            # Condition B02/11: Requestes item code / address.country_code / The country code based on localization should be returned
            elif ( "address.country_code" == item ):
                # Rule R25 ---->
                _item_builder_engine_faker_rule_executed = True
                # Trace ---->
                instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineFaker (20260213.151301), rule 25 of 31 has been executed", "DEBUG")
                # Trace <----
                # Action A01/11: Create local data / address.country_code / The country code based on localization should be returned
                local_data = Country.get_country_code(item_data, "ALPHA-2")
                # Action A05/01: Add to context / local / The local data will be stored into context
                instance.add_item(item, local_data)
                # Action A06/02: Print Log Message / not_consistent / The generated test data is not necessarily consistent with other dependent values!
                instance.add_rbt_log_message("The generated test data is not necessarily consistent with other dependent values!", "INFO")
                # Action A07/01: Return Item from context / item / Aktion ausführen
                return instance.get_item(item)
                # Rule R25 <----
            # Condition B02/12: Requestes item code / person.name / A complete name consisting of first name and last name should be returned.
            elif ( "person.name" == item ):
                # Condition B03/01: Item person.first_name is / unknown / In this case the item is not known in a concrete context.
                if ( None == instance.get_item("person.first_name") ):
                    # Condition B04/01: Item person.last_name is / unknown / In this case the item is not known in a concrete context.
                    if ( None == instance.get_item("person.last_name") ):
                        # Rule R26 ---->
                        _item_builder_engine_faker_rule_executed = True
                        # Trace ---->
                        instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineFaker (20260213.151301), rule 26 of 31 has been executed", "DEBUG")
                        # Trace <----
                        # Action A02/01: Create person.first_name and add to context / person.first_name / Aktion ausführen
                        match item_data.get("sex"):
                            case "f":
                                instance.add_item("person.first_name", fake.first_name_female())
                            case "m":
                                instance.add_item("person.first_name", fake.first_name_male())
                            case "d":
                                instance.add_item("person.first_name", fake.first_name_nonbinary())
                            case _:
                                instance.add_item("person.first_name", fake.first_name_nonbinary())
                        # Action A03/01: Create person.last_name and add to context / person.last_name / Aktion ausführen
                        match item_data.get("sex"):
                            case "f":
                                instance.add_item("person.last_name", fake.last_name_female())
                            case "m":
                                instance.add_item("person.last_name", fake.last_name_male())
                            case "d":
                                instance.add_item("person.last_name", fake.last_name_nonbinary())
                            case _:
                                instance.add_item("person.last_name", fake.last_name_nonbinary())
                        # Action A04/01: Compile person.name and add to context / person.name / Aktion ausführen
                        first_name = instance.get_item("person.first_name")
                        last_name = instance.get_item("person.last_name")
                        instance.add_item("person.name", f"{first_name} {last_name}")
                        # Action A07/01: Return Item from context / item / Aktion ausführen
                        return instance.get_item(item)
                        # Rule R26 <----
                    else:
                        # Rule R27 ---->
                        _item_builder_engine_faker_rule_executed = True
                        # Trace ---->
                        instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineFaker (20260213.151301), rule 27 of 31 has been executed", "DEBUG")
                        # Trace <----
                        # Action A02/01: Create person.first_name and add to context / person.first_name / Aktion ausführen
                        match item_data.get("sex"):
                            case "f":
                                instance.add_item("person.first_name", fake.first_name_female())
                            case "m":
                                instance.add_item("person.first_name", fake.first_name_male())
                            case "d":
                                instance.add_item("person.first_name", fake.first_name_nonbinary())
                            case _:
                                instance.add_item("person.first_name", fake.first_name_nonbinary())
                        # Action A04/01: Compile person.name and add to context / person.name / Aktion ausführen
                        first_name = instance.get_item("person.first_name")
                        last_name = instance.get_item("person.last_name")
                        instance.add_item("person.name", f"{first_name} {last_name}")
                        # Action A07/01: Return Item from context / item / Aktion ausführen
                        return instance.get_item(item)
                        # Rule R27 <----
                else:
                    # Condition B04/01: Item person.last_name is / unknown / In this case the item is not known in a concrete context.
                    if ( None == instance.get_item("person.last_name") ):
                        # Rule R28 ---->
                        _item_builder_engine_faker_rule_executed = True
                        # Trace ---->
                        instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineFaker (20260213.151301), rule 28 of 31 has been executed", "DEBUG")
                        # Trace <----
                        # Action A03/01: Create person.last_name and add to context / person.last_name / Aktion ausführen
                        match item_data.get("sex"):
                            case "f":
                                instance.add_item("person.last_name", fake.last_name_female())
                            case "m":
                                instance.add_item("person.last_name", fake.last_name_male())
                            case "d":
                                instance.add_item("person.last_name", fake.last_name_nonbinary())
                            case _:
                                instance.add_item("person.last_name", fake.last_name_nonbinary())
                        # Action A04/01: Compile person.name and add to context / person.name / Aktion ausführen
                        first_name = instance.get_item("person.first_name")
                        last_name = instance.get_item("person.last_name")
                        instance.add_item("person.name", f"{first_name} {last_name}")
                        # Action A07/01: Return Item from context / item / Aktion ausführen
                        return instance.get_item(item)
                        # Rule R28 <----
                    else:
                        # Rule R29 ---->
                        _item_builder_engine_faker_rule_executed = True
                        # Trace ---->
                        instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineFaker (20260213.151301), rule 29 of 31 has been executed", "DEBUG")
                        # Trace <----
                        # Action A04/01: Compile person.name and add to context / person.name / Aktion ausführen
                        first_name = instance.get_item("person.first_name")
                        last_name = instance.get_item("person.last_name")
                        instance.add_item("person.name", f"{first_name} {last_name}")
                        # Action A07/01: Return Item from context / item / Aktion ausführen
                        return instance.get_item(item)
                        # Rule R29 <----
            # Condition B02/13: Requestes item code / person.first_name / A first name should be returned.
            elif ( "person.first_name" == item ):
                # Rule R30 ---->
                _item_builder_engine_faker_rule_executed = True
                # Trace ---->
                instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineFaker (20260213.151301), rule 30 of 31 has been executed", "DEBUG")
                # Trace <----
                # Action A02/01: Create person.first_name and add to context / person.first_name / Aktion ausführen
                match item_data.get("sex"):
                    case "f":
                        instance.add_item("person.first_name", fake.first_name_female())
                    case "m":
                        instance.add_item("person.first_name", fake.first_name_male())
                    case "d":
                        instance.add_item("person.first_name", fake.first_name_nonbinary())
                    case _:
                        instance.add_item("person.first_name", fake.first_name_nonbinary())
                # Action A07/01: Return Item from context / item / Aktion ausführen
                return instance.get_item(item)
                # Rule R30 <----
            # Condition B02/14: Requestes item code / person.last_name / A last name should be returned.
            elif ( "person.last_name" == item ):
                # Rule R31 ---->
                _item_builder_engine_faker_rule_executed = True
                # Trace ---->
                instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineFaker (20260213.151301), rule 31 of 31 has been executed", "DEBUG")
                # Trace <----
                # Action A03/01: Create person.last_name and add to context / person.last_name / Aktion ausführen
                match item_data.get("sex"):
                    case "f":
                        instance.add_item("person.last_name", fake.last_name_female())
                    case "m":
                        instance.add_item("person.last_name", fake.last_name_male())
                    case "d":
                        instance.add_item("person.last_name", fake.last_name_nonbinary())
                    case _:
                        instance.add_item("person.last_name", fake.last_name_nonbinary())
                # Action A07/01: Return Item from context / item / Aktion ausführen
                return instance.get_item(item)
                # Rule R31 <----

        if not _item_builder_engine_faker_rule_executed:
            # Trace ---->
            instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineFaker (20260213.151301), rule 0 of 31 has been executed", "DEBUG")
            # Trace <----
            # Error ---->
            # profile LFET.Python.Error.ini not found
            # used LF-ET 2.4.1 (260127a) build in default
            raise AssertionError("no rule executed in decision table 'ItemBuilderEngineFaker'")
            # Error <----

# End of generated Python source code
# Generated by LF-ET 2.4.1 (260127a), https://www.lohrfink.de/lfet
