# *** WARNING: DO NOT MODIFY *** This is a generated Python source code!
#
# Generated by LF-ET 2.4.1 (260224a), https://www.lohrfink.de/lfet
# From decision table
# "E:/data/schweier/rbtfrmwrk/robotframework-syndata/lfet/ItemBuilderEngineGermany.lfet"
# 26.02.2026 09:54
#
# Changes to this code resulting from refactorings can be synchronised
# with LF-ET using the function "Scrapbook Import".
#
# Prolog Decision Table ---->
# $$BasicIndentLevel=2
from .person import Person
from .address import Address
from .finance import Finance as deFinance
from .traffic import Traffic


class ItemBuilderEngineGermany:

    @staticmethod
    def execute(instance, localization: str, keyword: str, item: str, item_data: dict):
        # Prolog Decision Table <----
        _item_builder_engine_germany_rule_executed: bool = False
        # Condition B02/01: Domain of the item is / address / address information
        if ( "address" == item.split(".")[0] ):
            # Condition B01/01: Context is / None / There is no set context.
            if ( None == instance.Get_Context() ):
                # Condition B03/01: Requested item code of domain "address" / address.address / An address consisting of street, house number, postal code, and city should be returned in two lines.
                if ( "address.address" == item ):
                    # Rule R01 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260226.095446), rule 1 of 28 has been executed", "DEBUG")
                    # Trace <----
                    # Action A04/01: Create full address data / address / The address data is generated and returned as a dictionary.
                    data_dict = Address.get_address_data(item_data)
                    # Action A12/03: Return created data from ... / dict / Depending on the type of test data, the dependent data for an item is also created in a dictionary. In this case, the item can be returned from the dictionary.
                    return data_dict.get(item, "")
                    # Rule R01 <----
                # Condition B03/02: Requested item code of domain "address" / address.address_country / An address consisting of street, house number, postal code, city, and state should be returned in three lines.
                elif ( "address.address_country" == item ):
                    # Rule R02 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260226.095446), rule 2 of 28 has been executed", "DEBUG")
                    # Trace <----
                    # Action A04/01: Create full address data / address / The address data is generated and returned as a dictionary.
                    data_dict = Address.get_address_data(item_data)
                    # Action A12/03: Return created data from ... / dict / Depending on the type of test data, the dependent data for an item is also created in a dictionary. In this case, the item can be returned from the dictionary.
                    return data_dict.get(item, "")
                    # Rule R02 <----
                # Condition B03/03: Requested item code of domain "address" / address.street_address / An address consisting of a street name and house number should be returned.
                elif ( "address.street_address" == item ):
                    # Rule R03 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260226.095446), rule 3 of 28 has been executed", "DEBUG")
                    # Trace <----
                    # Action A04/01: Create full address data / address / The address data is generated and returned as a dictionary.
                    data_dict = Address.get_address_data(item_data)
                    # Action A12/03: Return created data from ... / dict / Depending on the type of test data, the dependent data for an item is also created in a dictionary. In this case, the item can be returned from the dictionary.
                    return data_dict.get(item, "")
                    # Rule R03 <----
                # Condition B03/04: Requested item code of domain "address" / address.street / A street name shuold be returned.
                elif ( "address.street" == item ):
                    # Rule R04 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260226.095446), rule 4 of 28 has been executed", "DEBUG")
                    # Trace <----
                    # Action A04/01: Create full address data / address / The address data is generated and returned as a dictionary.
                    data_dict = Address.get_address_data(item_data)
                    # Action A12/03: Return created data from ... / dict / Depending on the type of test data, the dependent data for an item is also created in a dictionary. In this case, the item can be returned from the dictionary.
                    return data_dict.get(item, "")
                    # Rule R04 <----
                # Condition B03/05: Requested item code of domain "address" / address.house_number / A house number should be returned.
                elif ( "address.house_number" == item ):
                    # Rule R05 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260226.095446), rule 5 of 28 has been executed", "DEBUG")
                    # Trace <----
                    # Action A04/01: Create full address data / address / The address data is generated and returned as a dictionary.
                    data_dict = Address.get_address_data(item_data)
                    # Action A12/03: Return created data from ... / dict / Depending on the type of test data, the dependent data for an item is also created in a dictionary. In this case, the item can be returned from the dictionary.
                    return data_dict.get(item, "")
                    # Rule R05 <----
                # Condition B03/06: Requested item code of domain "address" / address.postcode_city / A city with its corresponding postal code should be returned.
                elif ( "address.postcode_city" == item ):
                    # Rule R06 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260226.095446), rule 6 of 28 has been executed", "DEBUG")
                    # Trace <----
                    # Action A04/01: Create full address data / address / The address data is generated and returned as a dictionary.
                    data_dict = Address.get_address_data(item_data)
                    # Action A12/03: Return created data from ... / dict / Depending on the type of test data, the dependent data for an item is also created in a dictionary. In this case, the item can be returned from the dictionary.
                    return data_dict.get(item, "")
                    # Rule R06 <----
                # Condition B03/07: Requested item code of domain "address" / address.postcode / A postal code should be returned.
                elif ( "address.postcode" == item ):
                    # Rule R07 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260226.095446), rule 7 of 28 has been executed", "DEBUG")
                    # Trace <----
                    # Action A04/01: Create full address data / address / The address data is generated and returned as a dictionary.
                    data_dict = Address.get_address_data(item_data)
                    # Action A12/03: Return created data from ... / dict / Depending on the type of test data, the dependent data for an item is also created in a dictionary. In this case, the item can be returned from the dictionary.
                    return data_dict.get(item, "")
                    # Rule R07 <----
                # Condition B03/08: Requested item code of domain "address" / address.city / A city is to be returned.
                elif ( "address.city" == item ):
                    # Rule R08 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260226.095446), rule 8 of 28 has been executed", "DEBUG")
                    # Trace <----
                    # Action A04/01: Create full address data / address / The address data is generated and returned as a dictionary.
                    data_dict = Address.get_address_data(item_data)
                    # Action A12/03: Return created data from ... / dict / Depending on the type of test data, the dependent data for an item is also created in a dictionary. In this case, the item can be returned from the dictionary.
                    return data_dict.get(item, "")
                    # Rule R08 <----
                # Condition B03/09: Requested item code of domain "address" / address.state / A federal state is to be returned.
                elif ( "address.state" == item ):
                    # Rule R09 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260226.095446), rule 9 of 28 has been executed", "DEBUG")
                    # Trace <----
                    # Action A04/01: Create full address data / address / The address data is generated and returned as a dictionary.
                    data_dict = Address.get_address_data(item_data)
                    # Action A12/03: Return created data from ... / dict / Depending on the type of test data, the dependent data for an item is also created in a dictionary. In this case, the item can be returned from the dictionary.
                    return data_dict.get(item, "")
                    # Rule R09 <----
                # Condition B03/10: Requested item code of domain "address" / address.country / A country name is to be returned.
                elif ( "address.country" == item ):
                    # Rule R10 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260226.095446), rule 10 of 28 has been executed", "DEBUG")
                    # Trace <----
                    # Action A12/05: Return created data from ... / common.country_name /
                    return instance.get_common_country_name(item_data, localization.split("_")[0].lower())
                    # Rule R10 <----
                # Condition B03/11: Requested item code of domain "address" / address.country_code / A country code  is to be returned.
                elif ( "address.country_code" == item ):
                    # Rule R11 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260226.095446), rule 11 of 28 has been executed", "DEBUG")
                    # Trace <----
                    # Action A12/06: Return created data from ... / common.country_code /
                    return instance.get_common_country_code(item_data, "ALPHA-2")
                    # Rule R11 <----
            else:
                # Condition B08/01: Geographical reference is / unknown / The geographic reference is not yet known for the context.
                if ( not ( instance.is_item_stored("location.ags") ) ):
                    # Rule R17 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260226.095446), rule 17 of 28 has been executed", "DEBUG")
                    # Trace <----
                    # Action A04/01: Create full address data / address / The address data is generated and returned as a dictionary.
                    data_dict = Address.get_address_data(item_data)
                    # Action A10/01: Add created data to context / dict / The individual items are added to the context from the generated dictionary.
                    for key, value in data_dict.items():
                        instance.add_item(key, value)
                    # Action A12/04: Return created data from ... / context / The return value is retrieved from the context.
                    return instance.get_item(item)
                    # Rule R17 <----
                else:
                    # Rule R18 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260226.095446), rule 18 of 28 has been executed", "DEBUG")
                    # Trace <----
                    # Action A03/02: Add geographical reference to item_data from ... / context / The value comes from context.
                    item_data["location.ags"] = instance.get_item("location.ags")
                    # Action A04/01: Create full address data / address / The address data is generated and returned as a dictionary.
                    data_dict = Address.get_address_data(item_data)
                    # Action A10/01: Add created data to context / dict / The individual items are added to the context from the generated dictionary.
                    for key, value in data_dict.items():
                        instance.add_item(key, value)
                    # Action A12/04: Return created data from ... / context / The return value is retrieved from the context.
                    return instance.get_item(item)
                    # Rule R18 <----
        # Condition B02/02: Domain of the item is / finance / data from the financial world
        elif ( "finance" == item.split(".")[0] ):
            # Condition B01/01: Context is / None / There is no set context.
            if ( None == instance.Get_Context() ):
                # Rule R12 ---->
                _item_builder_engine_germany_rule_executed = True
                # Trace ---->
                instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260226.095446), rule 12 of 28 has been executed", "DEBUG")
                # Trace <----
                # Action A05/01: Create full account data / account / The account data is generated and returned as a dictionary
                data_dict = deFinance.get_account_data(item_data)
                # Action A12/03: Return created data from ... / dict / Depending on the type of test data, the dependent data for an item is also created in a dictionary. In this case, the item can be returned from the dictionary.
                return data_dict.get(item, "")
                # Rule R12 <----
            else:
                # Rule R19 ---->
                _item_builder_engine_germany_rule_executed = True
                # Trace ---->
                instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260226.095446), rule 19 of 28 has been executed", "DEBUG")
                # Trace <----
                # Action A05/01: Create full account data / account / The account data is generated and returned as a dictionary
                data_dict = deFinance.get_account_data(item_data)
                # Action A10/01: Add created data to context / dict / The individual items are added to the context from the generated dictionary.
                for key, value in data_dict.items():
                    instance.add_item(key, value)
                # Action A12/04: Return created data from ... / context / The return value is retrieved from the context.
                return instance.get_item(item)
                # Rule R19 <----
        # Condition B02/03: Domain of the item is / person / personal data
        elif ( "person" == item.split(".")[0] ):
            # Condition B01/01: Context is / None / There is no set context.
            if ( None == instance.Get_Context() ):
                # Condition B04/01: Requested item code of domain "person" / person.name / A complete name consisting of first name and last name should be returned.
                if ( "person.name" == item ):
                    # Rule R13 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260226.095446), rule 13 of 28 has been executed", "DEBUG")
                    # Trace <----
                    # Action A08/01: Compile person.name and add to ... / local / Item is stored in a local variable.
                    local_data = Person.get_name(item_data)
                    # Action A12/02: Return created data from ... / local / The generated item is returned.
                    return local_data
                    # Rule R13 <----
                # Condition B04/02: Requested item code of domain "person" / person.first_name / A first name should be returned.
                elif ( "person.first_name" == item ):
                    # Rule R14 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260226.095446), rule 14 of 28 has been executed", "DEBUG")
                    # Trace <----
                    # Action A06/01: Create person.first_name and add to ... / local / Item is stored in a local variable.
                    local_data = Person.get_first_name(item_data)
                    # Action A12/02: Return created data from ... / local / The generated item is returned.
                    return local_data
                    # Rule R14 <----
                # Condition B04/03: Requested item code of domain "person" / person.last_name / A last name should be returned.
                elif ( "person.last_name" == item ):
                    # Rule R15 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260226.095446), rule 15 of 28 has been executed", "DEBUG")
                    # Trace <----
                    # Action A07/01: Create person.last_name and add to ... / local / Item is stored in a local variable.
                    local_data = Person.get_last_name(item_data)
                    # Action A12/02: Return created data from ... / local / The generated item is returned.
                    return local_data
                    # Rule R15 <----
            else:
                # Condition B04/01: Requested item code of domain "person" / person.name / A complete name consisting of first name and last name should be returned.
                if ( "person.name" == item ):
                    # Condition B06/01: Item person.first_name is / unknown / In this case the item is not known in a concrete context.
                    if ( None == instance.get_item("person.first_name") ):
                        # Condition B07/01: Item person.last_name is / unknown / In this case the item is not known in a concrete context.
                        if ( None == instance.get_item("person.last_name") ):
                            # Rule R20 ---->
                            _item_builder_engine_germany_rule_executed = True
                            # Trace ---->
                            instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260226.095446), rule 20 of 28 has been executed", "DEBUG")
                            # Trace <----
                            # Action A06/02: Create person.first_name and add to ... / context / Item is stored in context.
                            instance.add_item("person.first_name", Person.get_first_name(item_data))
                            # Action A07/02: Create person.last_name and add to ... / context / Item is stored in context.
                            instance.add_item("person.last_name", Person.get_last_name(item_data))
                            # Action A08/02: Compile person.name and add to ... / context / Item is stored in context.
                            first_name = instance.get_item("person.first_name")
                            last_name = instance.get_item("person.last_name")
                            instance.add_item("person.name", f"{first_name} {last_name}")
                            # Action A12/04: Return created data from ... / context / The return value is retrieved from the context.
                            return instance.get_item(item)
                            # Rule R20 <----
                        else:
                            # Rule R21 ---->
                            _item_builder_engine_germany_rule_executed = True
                            # Trace ---->
                            instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260226.095446), rule 21 of 28 has been executed", "DEBUG")
                            # Trace <----
                            # Action A06/02: Create person.first_name and add to ... / context / Item is stored in context.
                            instance.add_item("person.first_name", Person.get_first_name(item_data))
                            # Action A08/02: Compile person.name and add to ... / context / Item is stored in context.
                            first_name = instance.get_item("person.first_name")
                            last_name = instance.get_item("person.last_name")
                            instance.add_item("person.name", f"{first_name} {last_name}")
                            # Action A12/04: Return created data from ... / context / The return value is retrieved from the context.
                            return instance.get_item(item)
                            # Rule R21 <----
                    else:
                        # Condition B07/01: Item person.last_name is / unknown / In this case the item is not known in a concrete context.
                        if ( None == instance.get_item("person.last_name") ):
                            # Rule R22 ---->
                            _item_builder_engine_germany_rule_executed = True
                            # Trace ---->
                            instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260226.095446), rule 22 of 28 has been executed", "DEBUG")
                            # Trace <----
                            # Action A07/02: Create person.last_name and add to ... / context / Item is stored in context.
                            instance.add_item("person.last_name", Person.get_last_name(item_data))
                            # Action A08/02: Compile person.name and add to ... / context / Item is stored in context.
                            first_name = instance.get_item("person.first_name")
                            last_name = instance.get_item("person.last_name")
                            instance.add_item("person.name", f"{first_name} {last_name}")
                            # Action A12/04: Return created data from ... / context / The return value is retrieved from the context.
                            return instance.get_item(item)
                            # Rule R22 <----
                        else:
                            # Rule R23 ---->
                            _item_builder_engine_germany_rule_executed = True
                            # Trace ---->
                            instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260226.095446), rule 23 of 28 has been executed", "DEBUG")
                            # Trace <----
                            # Action A08/02: Compile person.name and add to ... / context / Item is stored in context.
                            first_name = instance.get_item("person.first_name")
                            last_name = instance.get_item("person.last_name")
                            instance.add_item("person.name", f"{first_name} {last_name}")
                            # Action A12/04: Return created data from ... / context / The return value is retrieved from the context.
                            return instance.get_item(item)
                            # Rule R23 <----
                # Condition B04/02: Requested item code of domain "person" / person.first_name / A first name should be returned.
                elif ( "person.first_name" == item ):
                    # Rule R24 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260226.095446), rule 24 of 28 has been executed", "DEBUG")
                    # Trace <----
                    # Action A06/02: Create person.first_name and add to ... / context / Item is stored in context.
                    instance.add_item("person.first_name", Person.get_first_name(item_data))
                    # Action A12/04: Return created data from ... / context / The return value is retrieved from the context.
                    return instance.get_item(item)
                    # Rule R24 <----
                # Condition B04/03: Requested item code of domain "person" / person.last_name / A last name should be returned.
                elif ( "person.last_name" == item ):
                    # Rule R25 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260226.095446), rule 25 of 28 has been executed", "DEBUG")
                    # Trace <----
                    # Action A07/02: Create person.last_name and add to ... / context / Item is stored in context.
                    instance.add_item("person.last_name", Person.get_last_name(item_data))
                    # Action A12/04: Return created data from ... / context / The return value is retrieved from the context.
                    return instance.get_item(item)
                    # Rule R25 <----
        # Condition B02/04: Domain of the item is / traffic / data from the field of land, air and water transport
        elif ( "traffic" == item.split(".")[0] ):
            # Condition B05/01: Requested item code of domain "traffic" / traffic.license_plate / licence plate for a motor vehicle
            if ( "traffic.license_plate" == item ):
                # Condition B01/01: Context is / None / There is no set context.
                if ( None == instance.Get_Context() ):
                    # Rule R16 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260226.095446), rule 16 of 28 has been executed", "DEBUG")
                    # Trace <----
                    # Action A01/01: Create geographical reference / location / A geographical reference is created that affects items related to one location.
                    geo_ref = Address.get_location(item_data)
                    if ( "" == geo_ref ):
                        instance.add_rbt_log_message("Since the filter conditions resulted in an empty set, they were ignored!", "WARN")
                        geo_ref = Address.get_location({})
                    instance.add_rbt_log_message(f"[Syndata] ItemBuilderEngineGermany: The location was set to ags='{geo_ref}'", "DEBUG")
                    # Action A03/01: Add geographical reference to item_data from ... / local / The value comes from variable.
                    item_data["location.ags"] = geo_ref
                    # Action A09/01: Create traffic data / license_plate / licence plate for a motor vehicle
                    local_data = Traffic.get_license_plate(item_data)
                    # Action A12/02: Return created data from ... / local / The generated item is returned.
                    return local_data
                    # Rule R16 <----
                else:
                    # Condition B08/01: Geographical reference is / unknown / The geographic reference is not yet known for the context.
                    if ( not ( instance.is_item_stored("location.ags") ) ):
                        # Rule R26 ---->
                        _item_builder_engine_germany_rule_executed = True
                        # Trace ---->
                        instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260226.095446), rule 26 of 28 has been executed", "DEBUG")
                        # Trace <----
                        # Action A01/01: Create geographical reference / location / A geographical reference is created that affects items related to one location.
                        geo_ref = Address.get_location(item_data)
                        if ( "" == geo_ref ):
                            instance.add_rbt_log_message("Since the filter conditions resulted in an empty set, they were ignored!", "WARN")
                            geo_ref = Address.get_location({})
                        instance.add_rbt_log_message(f"[Syndata] ItemBuilderEngineGermany: The location was set to ags='{geo_ref}'", "DEBUG")
                        # Action A02/01: Store geographical reference to ... / context / Item is stored in context.
                        instance.add_item("location.ags", geo_ref)
                        # Action A03/02: Add geographical reference to item_data from ... / context / The value comes from context.
                        item_data["location.ags"] = instance.get_item("location.ags")
                        # Action A09/01: Create traffic data / license_plate / licence plate for a motor vehicle
                        local_data = Traffic.get_license_plate(item_data)
                        # Action A10/02: Add created data to context / item / Individual value is stored in context.
                        instance.add_item(item, local_data)
                        # Action A12/04: Return created data from ... / context / The return value is retrieved from the context.
                        return instance.get_item(item)
                        # Rule R26 <----
                    else:
                        # Rule R27 ---->
                        _item_builder_engine_germany_rule_executed = True
                        # Trace ---->
                        instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260226.095446), rule 27 of 28 has been executed", "DEBUG")
                        # Trace <----
                        # Action A03/02: Add geographical reference to item_data from ... / context / The value comes from context.
                        item_data["location.ags"] = instance.get_item("location.ags")
                        # Action A09/01: Create traffic data / license_plate / licence plate for a motor vehicle
                        local_data = Traffic.get_license_plate(item_data)
                        # Action A10/02: Add created data to context / item / Individual value is stored in context.
                        instance.add_item(item, local_data)
                        # Action A12/04: Return created data from ... / context / The return value is retrieved from the context.
                        return instance.get_item(item)
                        # Rule R27 <----
            else:
                # Rule R28 ---->
                _item_builder_engine_germany_rule_executed = True
                # Trace ---->
                instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260226.095446), rule 28 of 28 has been executed", "DEBUG")
                # Trace <----
                # Action A11/01: Print Log Message / not_supported / Infomation that item is not supported.
                instance.add_rbt_log_message("The keyword \"{keyword}\" is not supported for localization \"{localization}\".", "INFO")
                # Action A12/01: Return created data from ... / empty / An empty string is returned.
                return ""
                # Rule R28 <----

        if not _item_builder_engine_germany_rule_executed:
            # Trace ---->
            instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260226.095446), rule 0 of 28 has been executed", "DEBUG")
            # Trace <----
            # Error ---->
            # profile LFET.Python.Error.ini not found
            # used LF-ET 2.4.1 (260224a) build in default
            raise AssertionError("no rule executed in decision table 'ItemBuilderEngineGermany'")
            # Error <----

# End of generated Python source code
# Generated by LF-ET 2.4.1 (260224a), https://www.lohrfink.de/lfet
