# *** WARNING: DO NOT MODIFY *** This is a generated Python source code!
#
# Generated by LF-ET 2.4.1 (260127a), https://www.lohrfink.de/lfet
# From decision table
# "E:/data/schweier/rbtfrmwrk/robotframework-syndata/lfet/ItemBuilderEngineGermany.lfet"
# 13.02.2026 15:13
#
# Changes to this code resulting from refactorings can be synchronised
# with LF-ET using the function "Scrapbook Import".
#
# Prolog Decision Table ---->
# $$BasicIndentLevel=2
from .person import Person
from .address import Address


class ItemBuilderEngineGermany:

    @staticmethod
    def execute(instance, localization: str, keyword: str, item: str, item_data: dict):
        # Prolog Decision Table <----
        _item_builder_engine_germany_rule_executed: bool = False
        # Condition B01/01: Context is / None / There is no set context.
        if ( None == instance.Get_Context() ):
            # Condition B02/01: Domain of the item is / address / address information
            if ( "address" == item.split(".")[0] ):
                # Condition B04/01: Requested item code of domain "address" / address.address / An address consisting of street, house number, postal code, and city should be returned in two lines.
                if ( "address.address" == item ):
                    # Rule R01 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260213.151301), rule 1 of 21 has been executed", "DEBUG")
                    # Trace <----
                    # Action A01/01: Create full address data / address / The address data is generated and returned as a dictionary.
                    data_dict = Address.get_address_data(item_data)
                    # Action A07/06: Return created data / from dict / Depending on the type of test data, the dependent data for an item is also created in a dictionary. In this case, the item can be returned from the dictionary.
                    return data_dict.setdefault(item, "")
                    # Rule R01 <----
                # Condition B04/02: Requested item code of domain "address" / address.address_country / An address consisting of street, house number, postal code, city, and state should be returned in three lines.
                elif ( "address.address_country" == item ):
                    # Rule R02 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260213.151301), rule 2 of 21 has been executed", "DEBUG")
                    # Trace <----
                    # Action A01/01: Create full address data / address / The address data is generated and returned as a dictionary.
                    data_dict = Address.get_address_data(item_data)
                    # Action A07/06: Return created data / from dict / Depending on the type of test data, the dependent data for an item is also created in a dictionary. In this case, the item can be returned from the dictionary.
                    return data_dict.setdefault(item, "")
                    # Rule R02 <----
                # Condition B04/03: Requested item code of domain "address" / address.street_address / An address consisting of a street name and house number should be returned.
                elif ( "address.street_address" == item ):
                    # Rule R03 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260213.151301), rule 3 of 21 has been executed", "DEBUG")
                    # Trace <----
                    # Action A01/01: Create full address data / address / The address data is generated and returned as a dictionary.
                    data_dict = Address.get_address_data(item_data)
                    # Action A07/06: Return created data / from dict / Depending on the type of test data, the dependent data for an item is also created in a dictionary. In this case, the item can be returned from the dictionary.
                    return data_dict.setdefault(item, "")
                    # Rule R03 <----
                # Condition B04/04: Requested item code of domain "address" / address.street / A street name shuold be returned.
                elif ( "address.street" == item ):
                    # Rule R04 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260213.151301), rule 4 of 21 has been executed", "DEBUG")
                    # Trace <----
                    # Action A01/01: Create full address data / address / The address data is generated and returned as a dictionary.
                    data_dict = Address.get_address_data(item_data)
                    # Action A07/06: Return created data / from dict / Depending on the type of test data, the dependent data for an item is also created in a dictionary. In this case, the item can be returned from the dictionary.
                    return data_dict.setdefault(item, "")
                    # Rule R04 <----
                # Condition B04/05: Requested item code of domain "address" / address.house_number / A house number should be returned.
                elif ( "address.house_number" == item ):
                    # Rule R05 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260213.151301), rule 5 of 21 has been executed", "DEBUG")
                    # Trace <----
                    # Action A01/01: Create full address data / address / The address data is generated and returned as a dictionary.
                    data_dict = Address.get_address_data(item_data)
                    # Action A07/06: Return created data / from dict / Depending on the type of test data, the dependent data for an item is also created in a dictionary. In this case, the item can be returned from the dictionary.
                    return data_dict.setdefault(item, "")
                    # Rule R05 <----
                # Condition B04/06: Requested item code of domain "address" / address.postcode_city / A city with its corresponding postal code should be returned.
                elif ( "address.postcode_city" == item ):
                    # Rule R06 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260213.151301), rule 6 of 21 has been executed", "DEBUG")
                    # Trace <----
                    # Action A01/01: Create full address data / address / The address data is generated and returned as a dictionary.
                    data_dict = Address.get_address_data(item_data)
                    # Action A07/06: Return created data / from dict / Depending on the type of test data, the dependent data for an item is also created in a dictionary. In this case, the item can be returned from the dictionary.
                    return data_dict.setdefault(item, "")
                    # Rule R06 <----
                # Condition B04/07: Requested item code of domain "address" / address.postcode / A postal code should be returned.
                elif ( "address.postcode" == item ):
                    # Rule R07 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260213.151301), rule 7 of 21 has been executed", "DEBUG")
                    # Trace <----
                    # Action A01/01: Create full address data / address / The address data is generated and returned as a dictionary.
                    data_dict = Address.get_address_data(item_data)
                    # Action A07/06: Return created data / from dict / Depending on the type of test data, the dependent data for an item is also created in a dictionary. In this case, the item can be returned from the dictionary.
                    return data_dict.setdefault(item, "")
                    # Rule R07 <----
                # Condition B04/08: Requested item code of domain "address" / address.city / A city is to be returned.
                elif ( "address.city" == item ):
                    # Rule R08 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260213.151301), rule 8 of 21 has been executed", "DEBUG")
                    # Trace <----
                    # Action A01/01: Create full address data / address / The address data is generated and returned as a dictionary.
                    data_dict = Address.get_address_data(item_data)
                    # Action A07/06: Return created data / from dict / Depending on the type of test data, the dependent data for an item is also created in a dictionary. In this case, the item can be returned from the dictionary.
                    return data_dict.setdefault(item, "")
                    # Rule R08 <----
                # Condition B04/09: Requested item code of domain "address" / address.state / A federal state is to be returned.
                elif ( "address.state" == item ):
                    # Rule R09 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260213.151301), rule 9 of 21 has been executed", "DEBUG")
                    # Trace <----
                    # Action A01/01: Create full address data / address / The address data is generated and returned as a dictionary.
                    data_dict = Address.get_address_data(item_data)
                    # Action A07/06: Return created data / from dict / Depending on the type of test data, the dependent data for an item is also created in a dictionary. In this case, the item can be returned from the dictionary.
                    return data_dict.setdefault(item, "")
                    # Rule R09 <----
                # Condition B04/10: Requested item code of domain "address" / address.country / A country name is to be returned.
                elif ( "address.country" == item ):
                    # Rule R10 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260213.151301), rule 10 of 21 has been executed", "DEBUG")
                    # Trace <----
                    # Action A07/04: Return created data / common.country_name /
                    return instance.get_common_country_name(item_data, localization.split("_")[0].lower())
                    # Rule R10 <----
                # Condition B04/11: Requested item code of domain "address" / address.country_code / A country code  is to be returned.
                elif ( "address.country_code" == item ):
                    # Rule R11 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260213.151301), rule 11 of 21 has been executed", "DEBUG")
                    # Trace <----
                    # Action A07/05: Return created data / common.country_code /
                    return instance.get_common_country_code(item_data, "ALPHA-2")
                    # Rule R11 <----
            # Condition B02/02: Domain of the item is / person / personal data
            elif ( "person" == item.split(".")[0] ):
                # Condition B03/01: Requested item code of domain "person" / person.name / A complete name consisting of first name and last name should be returned.
                if ( "person.name" == item ):
                    # Rule R12 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260213.151301), rule 12 of 21 has been executed", "DEBUG")
                    # Trace <----
                    # Action A07/01: Return created data / person.name /
                    return Person.get_name(item_data)
                    # Rule R12 <----
                # Condition B03/02: Requested item code of domain "person" / person.first_name / A first name should be returned.
                elif ( "person.first_name" == item ):
                    # Rule R13 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260213.151301), rule 13 of 21 has been executed", "DEBUG")
                    # Trace <----
                    # Action A07/02: Return created data / person.first_name /
                    return Person.get_first_name(item_data)
                    # Rule R13 <----
                # Condition B03/03: Requested item code of domain "person" / person.last_name / A last name should be returned.
                elif ( "person.last_name" == item ):
                    # Rule R14 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260213.151301), rule 14 of 21 has been executed", "DEBUG")
                    # Trace <----
                    # Action A07/03: Return created data / person.last_name /
                    return Person.get_last_name(item_data)
                    # Rule R14 <----
        else:
            # Condition B02/01: Domain of the item is / address / address information
            if ( "address" == item.split(".")[0] ):
                # Rule R15 ---->
                _item_builder_engine_germany_rule_executed = True
                # Trace ---->
                instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260213.151301), rule 15 of 21 has been executed", "DEBUG")
                # Trace <----
                # Action A01/01: Create full address data / address / The address data is generated and returned as a dictionary.
                data_dict = Address.get_address_data(item_data)
                # Action A05/01: Add created data to context / store dict / The individual items are added to the context from the generated dictionary.
                for key, value in data_dict.items():
                    instance.add_item(key, value)
                # Action A06/01: Return Item from context / item / Aktion ausführen
                return instance.get_item(item)
                # Rule R15 <----
            # Condition B02/02: Domain of the item is / person / personal data
            elif ( "person" == item.split(".")[0] ):
                # Condition B03/01: Requested item code of domain "person" / person.name / A complete name consisting of first name and last name should be returned.
                if ( "person.name" == item ):
                    # Condition B05/01: Item person.first_name is / unknown / In this case the item is not known in a concrete context.
                    if ( None == instance.get_item("person.first_name") ):
                        # Condition B06/01: Item person.last_name is / unknown / In this case the item is not known in a concrete context.
                        if ( None == instance.get_item("person.last_name") ):
                            # Rule R16 ---->
                            _item_builder_engine_germany_rule_executed = True
                            # Trace ---->
                            instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260213.151301), rule 16 of 21 has been executed", "DEBUG")
                            # Trace <----
                            # Action A02/01: Create person.first_name and add to context / person.first_name / Aktion ausführen
                            instance.add_item("person.first_name", Person.get_first_name(item_data))
                            # Action A03/01: Create person.last_name and add to context / person.last_name / Aktion ausführen
                            instance.add_item("person.last_name", Person.get_last_name(item_data))
                            # Action A04/01: Compile person.name and add to context / person.name / Aktion ausführen
                            first_name = instance.get_item("person.first_name")
                            last_name = instance.get_item("person.last_name")
                            instance.add_item("person.name", f"{first_name} {last_name}")
                            # Action A06/01: Return Item from context / item / Aktion ausführen
                            return instance.get_item(item)
                            # Rule R16 <----
                        else:
                            # Rule R17 ---->
                            _item_builder_engine_germany_rule_executed = True
                            # Trace ---->
                            instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260213.151301), rule 17 of 21 has been executed", "DEBUG")
                            # Trace <----
                            # Action A02/01: Create person.first_name and add to context / person.first_name / Aktion ausführen
                            instance.add_item("person.first_name", Person.get_first_name(item_data))
                            # Action A04/01: Compile person.name and add to context / person.name / Aktion ausführen
                            first_name = instance.get_item("person.first_name")
                            last_name = instance.get_item("person.last_name")
                            instance.add_item("person.name", f"{first_name} {last_name}")
                            # Action A06/01: Return Item from context / item / Aktion ausführen
                            return instance.get_item(item)
                            # Rule R17 <----
                    else:
                        # Condition B06/01: Item person.last_name is / unknown / In this case the item is not known in a concrete context.
                        if ( None == instance.get_item("person.last_name") ):
                            # Rule R18 ---->
                            _item_builder_engine_germany_rule_executed = True
                            # Trace ---->
                            instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260213.151301), rule 18 of 21 has been executed", "DEBUG")
                            # Trace <----
                            # Action A03/01: Create person.last_name and add to context / person.last_name / Aktion ausführen
                            instance.add_item("person.last_name", Person.get_last_name(item_data))
                            # Action A04/01: Compile person.name and add to context / person.name / Aktion ausführen
                            first_name = instance.get_item("person.first_name")
                            last_name = instance.get_item("person.last_name")
                            instance.add_item("person.name", f"{first_name} {last_name}")
                            # Action A06/01: Return Item from context / item / Aktion ausführen
                            return instance.get_item(item)
                            # Rule R18 <----
                        else:
                            # Rule R19 ---->
                            _item_builder_engine_germany_rule_executed = True
                            # Trace ---->
                            instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260213.151301), rule 19 of 21 has been executed", "DEBUG")
                            # Trace <----
                            # Action A04/01: Compile person.name and add to context / person.name / Aktion ausführen
                            first_name = instance.get_item("person.first_name")
                            last_name = instance.get_item("person.last_name")
                            instance.add_item("person.name", f"{first_name} {last_name}")
                            # Action A06/01: Return Item from context / item / Aktion ausführen
                            return instance.get_item(item)
                            # Rule R19 <----
                # Condition B03/02: Requested item code of domain "person" / person.first_name / A first name should be returned.
                elif ( "person.first_name" == item ):
                    # Rule R20 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260213.151301), rule 20 of 21 has been executed", "DEBUG")
                    # Trace <----
                    # Action A02/01: Create person.first_name and add to context / person.first_name / Aktion ausführen
                    instance.add_item("person.first_name", Person.get_first_name(item_data))
                    # Action A06/01: Return Item from context / item / Aktion ausführen
                    return instance.get_item(item)
                    # Rule R20 <----
                # Condition B03/03: Requested item code of domain "person" / person.last_name / A last name should be returned.
                elif ( "person.last_name" == item ):
                    # Rule R21 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260213.151301), rule 21 of 21 has been executed", "DEBUG")
                    # Trace <----
                    # Action A03/01: Create person.last_name and add to context / person.last_name / Aktion ausführen
                    instance.add_item("person.last_name", Person.get_last_name(item_data))
                    # Action A06/01: Return Item from context / item / Aktion ausführen
                    return instance.get_item(item)
                    # Rule R21 <----

        if not _item_builder_engine_germany_rule_executed:
            # Trace ---->
            instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260213.151301), rule 0 of 21 has been executed", "DEBUG")
            # Trace <----
            # Error ---->
            # profile LFET.Python.Error.ini not found
            # used LF-ET 2.4.1 (260127a) build in default
            raise AssertionError("no rule executed in decision table 'ItemBuilderEngineGermany'")
            # Error <----

# End of generated Python source code
# Generated by LF-ET 2.4.1 (260127a), https://www.lohrfink.de/lfet
