# *** WARNING: DO NOT MODIFY *** This is a generated Python source code!
#
# Generated by LF-ET 2.4.1 (260304a), https://www.lohrfink.de/lfet
# From decision table
# "E:/data/schweier/rbtfrmwrk/robotframework-syndata/lfet/ItemBuilderEngineGermany.lfet"
# 14.03.2026 12:49
#
# Changes to this code resulting from refactorings can be synchronised
# with LF-ET using the function "Scrapbook Import".
#
# Prolog Decision Table ---->
# $$BasicIndentLevel=2
from .person import Person
from .address import Address
from .communication import Communication
from .finance import Finance as deFinance
from .traffic import Traffic


class ItemBuilderEngineGermany:

    @staticmethod
    def execute(instance, localization: str, keyword: str, item: str, item_data: dict):
        # Prolog Decision Table <----
        _item_builder_engine_germany_rule_executed: bool = False
        # Condition B02/01: Domain of the item is / address / address information
        if ( "address" == item.split(".")[0] ):
            # Condition B01/01: Context is / None / There is no set context.
            if ( None == instance.Get_Context() ):
                # Condition B04/01: Requested item code of domain "address" / address.address / An address consisting of street, house number, postal code, and city should be returned in two lines.
                if ( "address.address" == item ):
                    # Rule R01 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 1 of 45 has been executed", "DEBUG")
                    # Trace <----
                    # Action A04/01: Create full address data / address / The address data is generated and returned as a dictionary.
                    data_dict = Address.get_address_data(item_data)
                    # Action A17/03: Return created data from ... / dict / Depending on the type of test data, the dependent data for an item is also created in a dictionary. In this case, the item can be returned from the dictionary.
                    return data_dict.get(item, "")
                    # Rule R01 <----
                # Condition B04/02: Requested item code of domain "address" / address.address_country / An address consisting of street, house number, postal code, city, and state should be returned in three lines.
                elif ( "address.address_country" == item ):
                    # Rule R02 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 2 of 45 has been executed", "DEBUG")
                    # Trace <----
                    # Action A04/01: Create full address data / address / The address data is generated and returned as a dictionary.
                    data_dict = Address.get_address_data(item_data)
                    # Action A17/03: Return created data from ... / dict / Depending on the type of test data, the dependent data for an item is also created in a dictionary. In this case, the item can be returned from the dictionary.
                    return data_dict.get(item, "")
                    # Rule R02 <----
                # Condition B04/03: Requested item code of domain "address" / address.street_address / An address consisting of a street name and house number should be returned.
                elif ( "address.street_address" == item ):
                    # Rule R03 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 3 of 45 has been executed", "DEBUG")
                    # Trace <----
                    # Action A04/01: Create full address data / address / The address data is generated and returned as a dictionary.
                    data_dict = Address.get_address_data(item_data)
                    # Action A17/03: Return created data from ... / dict / Depending on the type of test data, the dependent data for an item is also created in a dictionary. In this case, the item can be returned from the dictionary.
                    return data_dict.get(item, "")
                    # Rule R03 <----
                # Condition B04/04: Requested item code of domain "address" / address.street / A street name shuold be returned.
                elif ( "address.street" == item ):
                    # Rule R04 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 4 of 45 has been executed", "DEBUG")
                    # Trace <----
                    # Action A04/01: Create full address data / address / The address data is generated and returned as a dictionary.
                    data_dict = Address.get_address_data(item_data)
                    # Action A17/03: Return created data from ... / dict / Depending on the type of test data, the dependent data for an item is also created in a dictionary. In this case, the item can be returned from the dictionary.
                    return data_dict.get(item, "")
                    # Rule R04 <----
                # Condition B04/05: Requested item code of domain "address" / address.house_number / A house number should be returned.
                elif ( "address.house_number" == item ):
                    # Rule R05 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 5 of 45 has been executed", "DEBUG")
                    # Trace <----
                    # Action A04/01: Create full address data / address / The address data is generated and returned as a dictionary.
                    data_dict = Address.get_address_data(item_data)
                    # Action A17/03: Return created data from ... / dict / Depending on the type of test data, the dependent data for an item is also created in a dictionary. In this case, the item can be returned from the dictionary.
                    return data_dict.get(item, "")
                    # Rule R05 <----
                # Condition B04/06: Requested item code of domain "address" / address.postcode_city / A city with its corresponding postal code should be returned.
                elif ( "address.postcode_city" == item ):
                    # Rule R06 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 6 of 45 has been executed", "DEBUG")
                    # Trace <----
                    # Action A04/01: Create full address data / address / The address data is generated and returned as a dictionary.
                    data_dict = Address.get_address_data(item_data)
                    # Action A17/03: Return created data from ... / dict / Depending on the type of test data, the dependent data for an item is also created in a dictionary. In this case, the item can be returned from the dictionary.
                    return data_dict.get(item, "")
                    # Rule R06 <----
                # Condition B04/07: Requested item code of domain "address" / address.postcode / A postal code should be returned.
                elif ( "address.postcode" == item ):
                    # Rule R07 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 7 of 45 has been executed", "DEBUG")
                    # Trace <----
                    # Action A04/01: Create full address data / address / The address data is generated and returned as a dictionary.
                    data_dict = Address.get_address_data(item_data)
                    # Action A17/03: Return created data from ... / dict / Depending on the type of test data, the dependent data for an item is also created in a dictionary. In this case, the item can be returned from the dictionary.
                    return data_dict.get(item, "")
                    # Rule R07 <----
                # Condition B04/08: Requested item code of domain "address" / address.city / A city is to be returned.
                elif ( "address.city" == item ):
                    # Rule R08 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 8 of 45 has been executed", "DEBUG")
                    # Trace <----
                    # Action A04/01: Create full address data / address / The address data is generated and returned as a dictionary.
                    data_dict = Address.get_address_data(item_data)
                    # Action A17/03: Return created data from ... / dict / Depending on the type of test data, the dependent data for an item is also created in a dictionary. In this case, the item can be returned from the dictionary.
                    return data_dict.get(item, "")
                    # Rule R08 <----
                # Condition B04/09: Requested item code of domain "address" / address.state / A federal state is to be returned.
                elif ( "address.state" == item ):
                    # Rule R09 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 9 of 45 has been executed", "DEBUG")
                    # Trace <----
                    # Action A04/01: Create full address data / address / The address data is generated and returned as a dictionary.
                    data_dict = Address.get_address_data(item_data)
                    # Action A17/03: Return created data from ... / dict / Depending on the type of test data, the dependent data for an item is also created in a dictionary. In this case, the item can be returned from the dictionary.
                    return data_dict.get(item, "")
                    # Rule R09 <----
                # Condition B04/10: Requested item code of domain "address" / address.country / A country name is to be returned.
                elif ( "address.country" == item ):
                    # Rule R10 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 10 of 45 has been executed", "DEBUG")
                    # Trace <----
                    # Action A17/05: Return created data from ... / common.country_name /
                    return instance.get_common_country_name(item_data, localization.split("_")[0].lower())
                    # Rule R10 <----
                # Condition B04/11: Requested item code of domain "address" / address.country_code / A country code  is to be returned.
                elif ( "address.country_code" == item ):
                    # Rule R11 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 11 of 45 has been executed", "DEBUG")
                    # Trace <----
                    # Action A17/06: Return created data from ... / common.country_code /
                    return instance.get_common_country_code(item_data, "ALPHA-2")
                    # Rule R11 <----
            else:
                # Condition B11/01: Geographical reference is / unknown / The geographic reference is not yet known for the context.
                if ( not ( instance.is_item_stored("location.ags") ) ):
                    # Rule R20 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 20 of 45 has been executed", "DEBUG")
                    # Trace <----
                    # Action A04/01: Create full address data / address / The address data is generated and returned as a dictionary.
                    data_dict = Address.get_address_data(item_data)
                    # Action A15/01: Add created data to context / dict / The individual items are added to the context from the generated dictionary.
                    for key, value in data_dict.items():
                        instance.add_item(key, value)
                    # Action A17/04: Return created data from ... / context / The return value is retrieved from the context.
                    return instance.get_item(item)
                    # Rule R20 <----
                else:
                    # Rule R21 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 21 of 45 has been executed", "DEBUG")
                    # Trace <----
                    # Action A03/02: Add geographical reference to item_data from ... / context / The value comes from context.
                    item_data["location.ags"] = instance.get_item("location.ags")
                    # Action A04/01: Create full address data / address / The address data is generated and returned as a dictionary.
                    data_dict = Address.get_address_data(item_data)
                    # Action A15/01: Add created data to context / dict / The individual items are added to the context from the generated dictionary.
                    for key, value in data_dict.items():
                        instance.add_item(key, value)
                    # Action A17/04: Return created data from ... / context / The return value is retrieved from the context.
                    return instance.get_item(item)
                    # Rule R21 <----
        # Condition B02/02: Domain of the item is / communication / communication data
        elif ( "communication" == item.split(".")[0] ):
            # Condition B01/01: Context is / None / There is no set context.
            if ( None == instance.Get_Context() ):
                # Condition B03/01: Requested item code of domain "communication" / communication.email / email address
                if ( "communication.email" == item ):
                    # Rule R12 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 12 of 45 has been executed", "DEBUG")
                    # Trace <----
                    # Action A12/01: Create communication.email and add to ... / local / Item is stored in a local variable.
                    first_name = Person.get_first_name(item_data)
                    last_name = Person.get_last_name(item_data)
                    local_data = Communication.build_random_mail(item_data, first_name, last_name)
                    # Action A17/02: Return created data from ... / local / The generated item is returned.
                    return local_data
                    # Rule R12 <----
                # Condition B03/02: Requested item code of domain "communication" / communication.mobile / mobile phone number
                elif ( "communication.mobile" == item ):
                    # Rule R13 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 13 of 45 has been executed", "DEBUG")
                    # Trace <----
                    # Action A13/01: Create communication.mobile and add to ... / local / Item is stored in a local variable.
                    local_data = Communication.build_random_mobile_number(item_data)
                    # Action A17/02: Return created data from ... / local / The generated item is returned.
                    return local_data
                    # Rule R13 <----
            else:
                # Condition B03/01: Requested item code of domain "communication" / communication.email / email address
                if ( "communication.email" == item ):
                    # Condition B08/01: Item person.first_name is / unknown / In this case the item is not known in a concrete context.
                    if ( None == instance.get_item("person.first_name") ):
                        # Condition B09/01: Item person.last_name is / unknown / In this case the item is not known in a concrete context.
                        if ( None == instance.get_item("person.last_name") ):
                            # Rule R22 ---->
                            _item_builder_engine_germany_rule_executed = True
                            # Trace ---->
                            instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 22 of 45 has been executed", "DEBUG")
                            # Trace <----
                            # Action A06/01: Compile person.sex and add to ... / context / Item is stored in context.
                            item_data["preset.sex"] = item_data.get("preset.sex", item_data.get("sex", "*"))
                            instance.add_item("person.sex", Person.get_sex(item_data))
                            # Action A07/02: Create person.first_name and add to ... / context / Item is stored in context.
                            item_data.update({"person.sex":instance.get_item("person.sex")})
                            instance.add_item("person.first_name", Person.get_first_name(item_data))
                            # Action A08/02: Create person.last_name and add to ... / context / Item is stored in context.
                            instance.add_item("person.last_name", Person.get_last_name(item_data))
                            # Action A09/02: Compile person.name and add to ... / context / Item is stored in context.
                            first_name = instance.get_item("person.first_name")
                            last_name = instance.get_item("person.last_name")
                            instance.add_item("person.name", f"{first_name} {last_name}")
                            # Action A12/02: Create communication.email and add to ... / context / Item is stored in context.
                            instance.add_item("communication.email", Communication.build_random_mail(item_data, instance.get_item("person.first_name"), instance.get_item("person.last_name")))
                            # Action A17/04: Return created data from ... / context / The return value is retrieved from the context.
                            return instance.get_item(item)
                            # Rule R22 <----
                        else:
                            # Rule R23 ---->
                            _item_builder_engine_germany_rule_executed = True
                            # Trace ---->
                            instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 23 of 45 has been executed", "DEBUG")
                            # Trace <----
                            # Action A06/01: Compile person.sex and add to ... / context / Item is stored in context.
                            item_data["preset.sex"] = item_data.get("preset.sex", item_data.get("sex", "*"))
                            instance.add_item("person.sex", Person.get_sex(item_data))
                            # Action A07/02: Create person.first_name and add to ... / context / Item is stored in context.
                            item_data.update({"person.sex":instance.get_item("person.sex")})
                            instance.add_item("person.first_name", Person.get_first_name(item_data))
                            # Action A09/02: Compile person.name and add to ... / context / Item is stored in context.
                            first_name = instance.get_item("person.first_name")
                            last_name = instance.get_item("person.last_name")
                            instance.add_item("person.name", f"{first_name} {last_name}")
                            # Action A12/02: Create communication.email and add to ... / context / Item is stored in context.
                            instance.add_item("communication.email", Communication.build_random_mail(item_data, instance.get_item("person.first_name"), instance.get_item("person.last_name")))
                            # Action A17/04: Return created data from ... / context / The return value is retrieved from the context.
                            return instance.get_item(item)
                            # Rule R23 <----
                    else:
                        # Condition B09/01: Item person.last_name is / unknown / In this case the item is not known in a concrete context.
                        if ( None == instance.get_item("person.last_name") ):
                            # Rule R24 ---->
                            _item_builder_engine_germany_rule_executed = True
                            # Trace ---->
                            instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 24 of 45 has been executed", "DEBUG")
                            # Trace <----
                            # Action A08/02: Create person.last_name and add to ... / context / Item is stored in context.
                            instance.add_item("person.last_name", Person.get_last_name(item_data))
                            # Action A09/02: Compile person.name and add to ... / context / Item is stored in context.
                            first_name = instance.get_item("person.first_name")
                            last_name = instance.get_item("person.last_name")
                            instance.add_item("person.name", f"{first_name} {last_name}")
                            # Action A12/02: Create communication.email and add to ... / context / Item is stored in context.
                            instance.add_item("communication.email", Communication.build_random_mail(item_data, instance.get_item("person.first_name"), instance.get_item("person.last_name")))
                            # Action A17/04: Return created data from ... / context / The return value is retrieved from the context.
                            return instance.get_item(item)
                            # Rule R24 <----
                        else:
                            # Rule R25 ---->
                            _item_builder_engine_germany_rule_executed = True
                            # Trace ---->
                            instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 25 of 45 has been executed", "DEBUG")
                            # Trace <----
                            # Action A09/02: Compile person.name and add to ... / context / Item is stored in context.
                            first_name = instance.get_item("person.first_name")
                            last_name = instance.get_item("person.last_name")
                            instance.add_item("person.name", f"{first_name} {last_name}")
                            # Action A12/02: Create communication.email and add to ... / context / Item is stored in context.
                            instance.add_item("communication.email", Communication.build_random_mail(item_data, instance.get_item("person.first_name"), instance.get_item("person.last_name")))
                            # Action A17/04: Return created data from ... / context / The return value is retrieved from the context.
                            return instance.get_item(item)
                            # Rule R25 <----
                # Condition B03/02: Requested item code of domain "communication" / communication.mobile / mobile phone number
                elif ( "communication.mobile" == item ):
                    # Rule R26 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 26 of 45 has been executed", "DEBUG")
                    # Trace <----
                    # Action A13/02: Create communication.mobile and add to ... / context / Item is stored in context.
                    instance.add_item("communication.mobile", Communication.build_random_mobile_number(item_data))
                    # Action A17/04: Return created data from ... / context / The return value is retrieved from the context.
                    return instance.get_item(item)
                    # Rule R26 <----
        # Condition B02/03: Domain of the item is / finance / data from the financial world
        elif ( "finance" == item.split(".")[0] ):
            # Condition B01/01: Context is / None / There is no set context.
            if ( None == instance.Get_Context() ):
                # Rule R14 ---->
                _item_builder_engine_germany_rule_executed = True
                # Trace ---->
                instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 14 of 45 has been executed", "DEBUG")
                # Trace <----
                # Action A05/01: Create full account data / account / The account data is generated and returned as a dictionary
                data_dict = deFinance.get_account_data(item_data)
                # Action A17/03: Return created data from ... / dict / Depending on the type of test data, the dependent data for an item is also created in a dictionary. In this case, the item can be returned from the dictionary.
                return data_dict.get(item, "")
                # Rule R14 <----
            else:
                # Rule R27 ---->
                _item_builder_engine_germany_rule_executed = True
                # Trace ---->
                instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 27 of 45 has been executed", "DEBUG")
                # Trace <----
                # Action A05/01: Create full account data / account / The account data is generated and returned as a dictionary
                data_dict = deFinance.get_account_data(item_data)
                # Action A15/01: Add created data to context / dict / The individual items are added to the context from the generated dictionary.
                for key, value in data_dict.items():
                    instance.add_item(key, value)
                # Action A17/04: Return created data from ... / context / The return value is retrieved from the context.
                return instance.get_item(item)
                # Rule R27 <----
        # Condition B02/04: Domain of the item is / person / personal data
        elif ( "person" == item.split(".")[0] ):
            # Condition B01/01: Context is / None / There is no set context.
            if ( None == instance.Get_Context() ):
                # Condition B05/01: Requested item code of domain "person" / person.name / A complete name consisting of first name and last name should be returned.
                if ( "person.name" == item ):
                    # Rule R15 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 15 of 45 has been executed", "DEBUG")
                    # Trace <----
                    # Action A09/01: Compile person.name and add to ... / local / Item is stored in a local variable.
                    local_data = Person.get_name(item_data)
                    # Action A17/02: Return created data from ... / local / The generated item is returned.
                    return local_data
                    # Rule R15 <----
                # Condition B05/02: Requested item code of domain "person" / person.first_name / A first name should be returned.
                elif ( "person.first_name" == item ):
                    # Rule R16 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 16 of 45 has been executed", "DEBUG")
                    # Trace <----
                    # Action A07/01: Create person.first_name and add to ... / local / Item is stored in a local variable.
                    local_data = Person.get_first_name(item_data)
                    # Action A17/02: Return created data from ... / local / The generated item is returned.
                    return local_data
                    # Rule R16 <----
                # Condition B05/03: Requested item code of domain "person" / person.last_name / A last name should be returned.
                elif ( "person.last_name" == item ):
                    # Rule R17 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 17 of 45 has been executed", "DEBUG")
                    # Trace <----
                    # Action A08/01: Create person.last_name and add to ... / local / Item is stored in a local variable.
                    local_data = Person.get_last_name(item_data)
                    # Action A17/02: Return created data from ... / local / The generated item is returned.
                    return local_data
                    # Rule R17 <----
                else:
                    # Rule R18 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 18 of 45 has been executed", "DEBUG")
                    # Trace <----
                    # Action A11/01: Compile person.ssn and add to ... / local / Item is stored in a local variable.
                    local_data = Person.get_social_security_number(item_data)
                    # Action A17/02: Return created data from ... / local / The generated item is returned.
                    return local_data
                    # Rule R18 <----
            else:
                # Condition B05/01: Requested item code of domain "person" / person.name / A complete name consisting of first name and last name should be returned.
                if ( "person.name" == item ):
                    # Condition B08/01: Item person.first_name is / unknown / In this case the item is not known in a concrete context.
                    if ( None == instance.get_item("person.first_name") ):
                        # Condition B09/01: Item person.last_name is / unknown / In this case the item is not known in a concrete context.
                        if ( None == instance.get_item("person.last_name") ):
                            # Rule R28 ---->
                            _item_builder_engine_germany_rule_executed = True
                            # Trace ---->
                            instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 28 of 45 has been executed", "DEBUG")
                            # Trace <----
                            # Action A06/01: Compile person.sex and add to ... / context / Item is stored in context.
                            item_data["preset.sex"] = item_data.get("preset.sex", item_data.get("sex", "*"))
                            instance.add_item("person.sex", Person.get_sex(item_data))
                            # Action A07/02: Create person.first_name and add to ... / context / Item is stored in context.
                            item_data.update({"person.sex":instance.get_item("person.sex")})
                            instance.add_item("person.first_name", Person.get_first_name(item_data))
                            # Action A08/02: Create person.last_name and add to ... / context / Item is stored in context.
                            instance.add_item("person.last_name", Person.get_last_name(item_data))
                            # Action A09/02: Compile person.name and add to ... / context / Item is stored in context.
                            first_name = instance.get_item("person.first_name")
                            last_name = instance.get_item("person.last_name")
                            instance.add_item("person.name", f"{first_name} {last_name}")
                            # Action A17/04: Return created data from ... / context / The return value is retrieved from the context.
                            return instance.get_item(item)
                            # Rule R28 <----
                        else:
                            # Rule R29 ---->
                            _item_builder_engine_germany_rule_executed = True
                            # Trace ---->
                            instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 29 of 45 has been executed", "DEBUG")
                            # Trace <----
                            # Action A06/01: Compile person.sex and add to ... / context / Item is stored in context.
                            item_data["preset.sex"] = item_data.get("preset.sex", item_data.get("sex", "*"))
                            instance.add_item("person.sex", Person.get_sex(item_data))
                            # Action A07/02: Create person.first_name and add to ... / context / Item is stored in context.
                            item_data.update({"person.sex":instance.get_item("person.sex")})
                            instance.add_item("person.first_name", Person.get_first_name(item_data))
                            # Action A09/02: Compile person.name and add to ... / context / Item is stored in context.
                            first_name = instance.get_item("person.first_name")
                            last_name = instance.get_item("person.last_name")
                            instance.add_item("person.name", f"{first_name} {last_name}")
                            # Action A17/04: Return created data from ... / context / The return value is retrieved from the context.
                            return instance.get_item(item)
                            # Rule R29 <----
                    else:
                        # Condition B09/01: Item person.last_name is / unknown / In this case the item is not known in a concrete context.
                        if ( None == instance.get_item("person.last_name") ):
                            # Rule R30 ---->
                            _item_builder_engine_germany_rule_executed = True
                            # Trace ---->
                            instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 30 of 45 has been executed", "DEBUG")
                            # Trace <----
                            # Action A08/02: Create person.last_name and add to ... / context / Item is stored in context.
                            instance.add_item("person.last_name", Person.get_last_name(item_data))
                            # Action A09/02: Compile person.name and add to ... / context / Item is stored in context.
                            first_name = instance.get_item("person.first_name")
                            last_name = instance.get_item("person.last_name")
                            instance.add_item("person.name", f"{first_name} {last_name}")
                            # Action A17/04: Return created data from ... / context / The return value is retrieved from the context.
                            return instance.get_item(item)
                            # Rule R30 <----
                        else:
                            # Rule R31 ---->
                            _item_builder_engine_germany_rule_executed = True
                            # Trace ---->
                            instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 31 of 45 has been executed", "DEBUG")
                            # Trace <----
                            # Action A09/02: Compile person.name and add to ... / context / Item is stored in context.
                            first_name = instance.get_item("person.first_name")
                            last_name = instance.get_item("person.last_name")
                            instance.add_item("person.name", f"{first_name} {last_name}")
                            # Action A17/04: Return created data from ... / context / The return value is retrieved from the context.
                            return instance.get_item(item)
                            # Rule R31 <----
                # Condition B05/02: Requested item code of domain "person" / person.first_name / A first name should be returned.
                elif ( "person.first_name" == item ):
                    # Condition B07/01: Item person.sex is / unknown / In this case the item is not known in a concrete context.
                    if ( None == instance.get_item("person.sex") ):
                        # Rule R32 ---->
                        _item_builder_engine_germany_rule_executed = True
                        # Trace ---->
                        instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 32 of 45 has been executed", "DEBUG")
                        # Trace <----
                        # Action A06/01: Compile person.sex and add to ... / context / Item is stored in context.
                        item_data["preset.sex"] = item_data.get("preset.sex", item_data.get("sex", "*"))
                        instance.add_item("person.sex", Person.get_sex(item_data))
                        # Action A07/02: Create person.first_name and add to ... / context / Item is stored in context.
                        item_data.update({"person.sex":instance.get_item("person.sex")})
                        instance.add_item("person.first_name", Person.get_first_name(item_data))
                        # Action A17/04: Return created data from ... / context / The return value is retrieved from the context.
                        return instance.get_item(item)
                        # Rule R32 <----
                    else:
                        # Rule R33 ---->
                        _item_builder_engine_germany_rule_executed = True
                        # Trace ---->
                        instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 33 of 45 has been executed", "DEBUG")
                        # Trace <----
                        # Action A07/02: Create person.first_name and add to ... / context / Item is stored in context.
                        item_data.update({"person.sex":instance.get_item("person.sex")})
                        instance.add_item("person.first_name", Person.get_first_name(item_data))
                        # Action A17/04: Return created data from ... / context / The return value is retrieved from the context.
                        return instance.get_item(item)
                        # Rule R33 <----
                # Condition B05/03: Requested item code of domain "person" / person.last_name / A last name should be returned.
                elif ( "person.last_name" == item ):
                    # Rule R34 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 34 of 45 has been executed", "DEBUG")
                    # Trace <----
                    # Action A08/02: Create person.last_name and add to ... / context / Item is stored in context.
                    instance.add_item("person.last_name", Person.get_last_name(item_data))
                    # Action A17/04: Return created data from ... / context / The return value is retrieved from the context.
                    return instance.get_item(item)
                    # Rule R34 <----
                else:
                    # Condition B07/01: Item person.sex is / unknown / In this case the item is not known in a concrete context.
                    if ( None == instance.get_item("person.sex") ):
                        # Condition B09/01: Item person.last_name is / unknown / In this case the item is not known in a concrete context.
                        if ( None == instance.get_item("person.last_name") ):
                            # Condition B10/01: Item person.dob is / unknown / In this case the item is not known in a concrete context.
                            if ( None == instance.get_item("person.dob") ):
                                # Rule R35 ---->
                                _item_builder_engine_germany_rule_executed = True
                                # Trace ---->
                                instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 35 of 45 has been executed", "DEBUG")
                                # Trace <----
                                # Action A06/01: Compile person.sex and add to ... / context / Item is stored in context.
                                item_data["preset.sex"] = item_data.get("preset.sex", item_data.get("sex", "*"))
                                instance.add_item("person.sex", Person.get_sex(item_data))
                                # Action A08/02: Create person.last_name and add to ... / context / Item is stored in context.
                                instance.add_item("person.last_name", Person.get_last_name(item_data))
                                # Action A10/01: Compile person.dob and add to ... / context / Item is stored in context.
                                instance.add_item("person.dob", Person.get_date_of_birth(item_data))
                                # Action A11/02: Compile person.ssn and add to ... / context / Item is stored in context.
                                item_data.update({"person.last_name":instance.get_item("person.last_name"), "person.dob":instance.get_item("person.dob"), "person.sex":instance.get_item("person.sex")})
                                instance.add_item("person.ssn", Person.get_social_security_number(item_data))
                                # Action A17/04: Return created data from ... / context / The return value is retrieved from the context.
                                return instance.get_item(item)
                                # Rule R35 <----
                            else:
                                # Rule R36 ---->
                                _item_builder_engine_germany_rule_executed = True
                                # Trace ---->
                                instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 36 of 45 has been executed", "DEBUG")
                                # Trace <----
                                # Action A06/01: Compile person.sex and add to ... / context / Item is stored in context.
                                item_data["preset.sex"] = item_data.get("preset.sex", item_data.get("sex", "*"))
                                instance.add_item("person.sex", Person.get_sex(item_data))
                                # Action A08/02: Create person.last_name and add to ... / context / Item is stored in context.
                                instance.add_item("person.last_name", Person.get_last_name(item_data))
                                # Action A11/02: Compile person.ssn and add to ... / context / Item is stored in context.
                                item_data.update({"person.last_name":instance.get_item("person.last_name"), "person.dob":instance.get_item("person.dob"), "person.sex":instance.get_item("person.sex")})
                                instance.add_item("person.ssn", Person.get_social_security_number(item_data))
                                # Action A17/04: Return created data from ... / context / The return value is retrieved from the context.
                                return instance.get_item(item)
                                # Rule R36 <----
                        else:
                            # Condition B10/01: Item person.dob is / unknown / In this case the item is not known in a concrete context.
                            if ( None == instance.get_item("person.dob") ):
                                # Rule R37 ---->
                                _item_builder_engine_germany_rule_executed = True
                                # Trace ---->
                                instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 37 of 45 has been executed", "DEBUG")
                                # Trace <----
                                # Action A06/01: Compile person.sex and add to ... / context / Item is stored in context.
                                item_data["preset.sex"] = item_data.get("preset.sex", item_data.get("sex", "*"))
                                instance.add_item("person.sex", Person.get_sex(item_data))
                                # Action A10/01: Compile person.dob and add to ... / context / Item is stored in context.
                                instance.add_item("person.dob", Person.get_date_of_birth(item_data))
                                # Action A11/02: Compile person.ssn and add to ... / context / Item is stored in context.
                                item_data.update({"person.last_name":instance.get_item("person.last_name"), "person.dob":instance.get_item("person.dob"), "person.sex":instance.get_item("person.sex")})
                                instance.add_item("person.ssn", Person.get_social_security_number(item_data))
                                # Action A17/04: Return created data from ... / context / The return value is retrieved from the context.
                                return instance.get_item(item)
                                # Rule R37 <----
                            else:
                                # Rule R38 ---->
                                _item_builder_engine_germany_rule_executed = True
                                # Trace ---->
                                instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 38 of 45 has been executed", "DEBUG")
                                # Trace <----
                                # Action A06/01: Compile person.sex and add to ... / context / Item is stored in context.
                                item_data["preset.sex"] = item_data.get("preset.sex", item_data.get("sex", "*"))
                                instance.add_item("person.sex", Person.get_sex(item_data))
                                # Action A11/02: Compile person.ssn and add to ... / context / Item is stored in context.
                                item_data.update({"person.last_name":instance.get_item("person.last_name"), "person.dob":instance.get_item("person.dob"), "person.sex":instance.get_item("person.sex")})
                                instance.add_item("person.ssn", Person.get_social_security_number(item_data))
                                # Action A17/04: Return created data from ... / context / The return value is retrieved from the context.
                                return instance.get_item(item)
                                # Rule R38 <----
                    else:
                        # Condition B09/01: Item person.last_name is / unknown / In this case the item is not known in a concrete context.
                        if ( None == instance.get_item("person.last_name") ):
                            # Condition B10/01: Item person.dob is / unknown / In this case the item is not known in a concrete context.
                            if ( None == instance.get_item("person.dob") ):
                                # Rule R39 ---->
                                _item_builder_engine_germany_rule_executed = True
                                # Trace ---->
                                instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 39 of 45 has been executed", "DEBUG")
                                # Trace <----
                                # Action A08/02: Create person.last_name and add to ... / context / Item is stored in context.
                                instance.add_item("person.last_name", Person.get_last_name(item_data))
                                # Action A10/01: Compile person.dob and add to ... / context / Item is stored in context.
                                instance.add_item("person.dob", Person.get_date_of_birth(item_data))
                                # Action A11/02: Compile person.ssn and add to ... / context / Item is stored in context.
                                item_data.update({"person.last_name":instance.get_item("person.last_name"), "person.dob":instance.get_item("person.dob"), "person.sex":instance.get_item("person.sex")})
                                instance.add_item("person.ssn", Person.get_social_security_number(item_data))
                                # Action A17/04: Return created data from ... / context / The return value is retrieved from the context.
                                return instance.get_item(item)
                                # Rule R39 <----
                            else:
                                # Rule R40 ---->
                                _item_builder_engine_germany_rule_executed = True
                                # Trace ---->
                                instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 40 of 45 has been executed", "DEBUG")
                                # Trace <----
                                # Action A08/02: Create person.last_name and add to ... / context / Item is stored in context.
                                instance.add_item("person.last_name", Person.get_last_name(item_data))
                                # Action A11/02: Compile person.ssn and add to ... / context / Item is stored in context.
                                item_data.update({"person.last_name":instance.get_item("person.last_name"), "person.dob":instance.get_item("person.dob"), "person.sex":instance.get_item("person.sex")})
                                instance.add_item("person.ssn", Person.get_social_security_number(item_data))
                                # Action A17/04: Return created data from ... / context / The return value is retrieved from the context.
                                return instance.get_item(item)
                                # Rule R40 <----
                        else:
                            # Condition B10/01: Item person.dob is / unknown / In this case the item is not known in a concrete context.
                            if ( None == instance.get_item("person.dob") ):
                                # Rule R41 ---->
                                _item_builder_engine_germany_rule_executed = True
                                # Trace ---->
                                instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 41 of 45 has been executed", "DEBUG")
                                # Trace <----
                                # Action A10/01: Compile person.dob and add to ... / context / Item is stored in context.
                                instance.add_item("person.dob", Person.get_date_of_birth(item_data))
                                # Action A11/02: Compile person.ssn and add to ... / context / Item is stored in context.
                                item_data.update({"person.last_name":instance.get_item("person.last_name"), "person.dob":instance.get_item("person.dob"), "person.sex":instance.get_item("person.sex")})
                                instance.add_item("person.ssn", Person.get_social_security_number(item_data))
                                # Action A17/04: Return created data from ... / context / The return value is retrieved from the context.
                                return instance.get_item(item)
                                # Rule R41 <----
                            else:
                                # Rule R42 ---->
                                _item_builder_engine_germany_rule_executed = True
                                # Trace ---->
                                instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 42 of 45 has been executed", "DEBUG")
                                # Trace <----
                                # Action A11/02: Compile person.ssn and add to ... / context / Item is stored in context.
                                item_data.update({"person.last_name":instance.get_item("person.last_name"), "person.dob":instance.get_item("person.dob"), "person.sex":instance.get_item("person.sex")})
                                instance.add_item("person.ssn", Person.get_social_security_number(item_data))
                                # Action A17/04: Return created data from ... / context / The return value is retrieved from the context.
                                return instance.get_item(item)
                                # Rule R42 <----
        # Condition B02/05: Domain of the item is / traffic / data from the field of land, air and water transport
        elif ( "traffic" == item.split(".")[0] ):
            # Condition B06/01: Requested item code of domain "traffic" / traffic.license_plate / licence plate for a motor vehicle
            if ( "traffic.license_plate" == item ):
                # Condition B01/01: Context is / None / There is no set context.
                if ( None == instance.Get_Context() ):
                    # Rule R19 ---->
                    _item_builder_engine_germany_rule_executed = True
                    # Trace ---->
                    instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 19 of 45 has been executed", "DEBUG")
                    # Trace <----
                    # Action A01/01: Create geographical reference / location / A geographical reference is created that affects items related to one location.
                    geo_ref = Address.get_location(item_data)
                    if ( "" == geo_ref ):
                        instance.add_rbt_log_message("Since the filter conditions resulted in an empty set, they were ignored!", "WARN")
                        geo_ref = Address.get_location({})
                    instance.add_rbt_log_message(f"[Syndata] ItemBuilderEngineGermany: The location was set to ags='{geo_ref}'", "DEBUG")
                    # Action A03/01: Add geographical reference to item_data from ... / local / The value comes from variable.
                    item_data["location.ags"] = geo_ref
                    # Action A14/01: Create traffic data / license_plate / licence plate for a motor vehicle
                    local_data = Traffic.get_license_plate(item_data)
                    # Action A17/02: Return created data from ... / local / The generated item is returned.
                    return local_data
                    # Rule R19 <----
                else:
                    # Condition B11/01: Geographical reference is / unknown / The geographic reference is not yet known for the context.
                    if ( not ( instance.is_item_stored("location.ags") ) ):
                        # Rule R43 ---->
                        _item_builder_engine_germany_rule_executed = True
                        # Trace ---->
                        instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 43 of 45 has been executed", "DEBUG")
                        # Trace <----
                        # Action A01/01: Create geographical reference / location / A geographical reference is created that affects items related to one location.
                        geo_ref = Address.get_location(item_data)
                        if ( "" == geo_ref ):
                            instance.add_rbt_log_message("Since the filter conditions resulted in an empty set, they were ignored!", "WARN")
                            geo_ref = Address.get_location({})
                        instance.add_rbt_log_message(f"[Syndata] ItemBuilderEngineGermany: The location was set to ags='{geo_ref}'", "DEBUG")
                        # Action A02/01: Store geographical reference to ... / context / Item is stored in context.
                        instance.add_item("location.ags", geo_ref)
                        # Action A03/02: Add geographical reference to item_data from ... / context / The value comes from context.
                        item_data["location.ags"] = instance.get_item("location.ags")
                        # Action A14/01: Create traffic data / license_plate / licence plate for a motor vehicle
                        local_data = Traffic.get_license_plate(item_data)
                        # Action A15/02: Add created data to context / item / Individual value is stored in context.
                        instance.add_item(item, local_data)
                        # Action A17/04: Return created data from ... / context / The return value is retrieved from the context.
                        return instance.get_item(item)
                        # Rule R43 <----
                    else:
                        # Rule R44 ---->
                        _item_builder_engine_germany_rule_executed = True
                        # Trace ---->
                        instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 44 of 45 has been executed", "DEBUG")
                        # Trace <----
                        # Action A03/02: Add geographical reference to item_data from ... / context / The value comes from context.
                        item_data["location.ags"] = instance.get_item("location.ags")
                        # Action A14/01: Create traffic data / license_plate / licence plate for a motor vehicle
                        local_data = Traffic.get_license_plate(item_data)
                        # Action A15/02: Add created data to context / item / Individual value is stored in context.
                        instance.add_item(item, local_data)
                        # Action A17/04: Return created data from ... / context / The return value is retrieved from the context.
                        return instance.get_item(item)
                        # Rule R44 <----
            else:
                # Rule R45 ---->
                _item_builder_engine_germany_rule_executed = True
                # Trace ---->
                instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 45 of 45 has been executed", "DEBUG")
                # Trace <----
                # Action A16/01: Print Log Message / not_supported / Infomation that item is not supported.
                instance.add_rbt_log_message("The keyword \"{keyword}\" is not supported for localization \"{localization}\".", "INFO")
                # Action A17/01: Return created data from ... / empty / An empty string is returned.
                return ""
                # Rule R45 <----

        if not _item_builder_engine_germany_rule_executed:
            # Trace ---->
            instance.add_rbt_log_message("[SynData] Decision table ItemBuilderEngineGermany (20260314.124926), rule 0 of 45 has been executed", "DEBUG")
            # Trace <----
            # Error ---->
            # profile LFET.Python.Error.ini not found
            # used LF-ET 2.4.1 (260304a) build in default
            raise AssertionError("no rule executed in decision table 'ItemBuilderEngineGermany'")
            # Error <----

# End of generated Python source code
# Generated by LF-ET 2.4.1 (260304a), https://www.lohrfink.de/lfet
